module;
#include <cstdint>

export module rhi:resources;
import :types;
import :handles;
import :sync;
import :descriptors;

export namespace rhi
{

    // ---- Texture views ----

    /// \brief Selects a typed mip/layer view of a texture.
    ///
    /// Use a view when an operation addresses fewer subresources than the full
    /// texture or needs a compatible format reinterpretation.
    struct TextureView
    {
        TextureHandle    Texture; ///< Texture containing the selected subresources.
        SubresourceRange Range{}; ///< Mip levels and array layers visible through the view.
        TextureDimension ViewDimension{TextureDimension::Tex2D}; ///< Dimension exposed to the consuming operation.
        Format           Format{Format::Undefined}; ///< Compatible view format; Undefined inherits the texture format.
    };

    // ---- Buffer information ----

    /// \brief Describes a live buffer returned by IDevice::GetBufferInfo().
    struct BufferInfo
    {
        uint64_t    Size{0};         ///< Allocation size in bytes.
        uint32_t    Stride{0};       ///< Element stride in bytes; zero denotes raw storage.
        BufferUsage Usage{};         ///< Usage flags selected at creation.
        MemoryType  MemoryType{};    ///< CPU/GPU visibility selected at creation.
        GpuAddress  DeviceAddress{}; ///< Shader-visible address, invalid when not requested.
    };

    // ---- Indirect commands ----

    /// \brief GPU-readable arguments consumed by ICommandList::DrawIndirect().
    ///
    /// Store one or more entries in a buffer created with
    /// BufferUsage::IndirectArgs, transition it to ResourceState::IndirectArgument,
    /// and pass its byte offset and stride to DrawIndirect().
    struct DrawIndirectArgs
    {
        uint32_t VertexCount{0};   ///< Vertices generated per instance.
        uint32_t InstanceCount{1}; ///< Instances generated by the draw.
        uint32_t FirstVertex{0};   ///< First vertex index supplied to the shader.
        uint32_t FirstInstance{0}; ///< First instance index supplied to the shader.
    };

    /// \brief GPU-readable arguments consumed by ICommandList::DrawIndexedIndirect().
    /// \note The field order is the portable GPU indirect-command layout; do not add host-only fields.
    struct DrawIndexedIndirectArgs
    {
        uint32_t IndexCount{0};    ///< Indices consumed per instance.
        uint32_t InstanceCount{1}; ///< Instances generated by the draw.
        uint32_t FirstIndex{0};    ///< First element read from the bound index buffer.
        int32_t  VertexOffset{0};  ///< Signed offset added to each index.
        uint32_t FirstInstance{0}; ///< First instance index supplied to the shader.
    };

    /// \brief GPU-readable thread-group counts consumed by ICommandList::DispatchIndirect().
    /// \note Place this value in a buffer ready for ResourceState::IndirectArgument access.
    struct DispatchIndirectArgs
    {
        uint32_t X{1}; ///< Thread-group count in X.
        uint32_t Y{1}; ///< Thread-group count in Y.
        uint32_t Z{1}; ///< Thread-group count in Z.
    };

} // namespace rhi
